#pragma config(Motor,  motor7,          LMotor,        tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor9,          MMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         RMotor,        tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		setMotorSpeed(RMotor, (getJoystickValue(ChD)) * 1.27);
		setMotorSpeed(LMotor, (getJoystickValue(ChA)) * 1.27);
		setMotorSpeed(MMotor, (getJoystickValue(ChB)) * 1.27);
	}
}
