#pragma config(Sensor, port5,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          LeftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          RightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         BarLift,       tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  motor11,         Claw,          tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {

	int threshold = 15;
	int wallHeight = 374;
	int postHeight = 1450;
	resetMotorEncoder(BarLift);

	bool moveToHeight = false;
	while(true) {

		//The code for the Left Joystick
		if (getJoystickValue(ChA)	> threshold || getJoystickValue(ChA) < -threshold) {
			setMotorSpeed(LeftMotor, getJoystickValue(ChA)*0.85);
		}
		else {
			setMotorSpeed(LeftMotor, 0);
		}


		//The code for the Right Joystick
		if (getJoystickValue(ChD)	> threshold || getJoystickValue(ChD) < -threshold) {
			setMotorSpeed(RightMotor, getJoystickValue(ChD)*0.85);
		}
		else {
			setMotorSpeed(RightMotor, 0);
		}


		//The code for the Bar Lift
		if (getJoystickValue(BtnLUp) == 1) {
			setMotorSpeed(BarLift, 75);
			moveToHeight = false;
		}
		else if(getJoystickValue(BtnLDown) == 1) {
			setMotorSpeed(BarLift, -75);
			moveToHeight = false;
		}
		//The code for the 4 bar lift going up to the perfect position
		else if (getJoystickValue(BtnRDown) == 1) {
			int startingPeg = -(getMotorEncoder(BarLift) - wallHeight);
			moveToHeight = true;

			moveMotorTarget(BarLift, startingPeg, 100);
		}
		else if (getJoystickValue(BtnRUp) == 1) {
			int post = -(getMotorEncoder(BarLift) - postHeight);

			moveMotorTarget(BarLift, post, 100);
			moveToHeight = true;
		}
		else {
			if (moveToHeight == false) {
				setMotorSpeed(BarLift, 0);
			}
		}

	}

}
