#pragma config(Sensor, port5, Gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          LeftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          RightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         BarLift,       tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// global variables
int SPEED = 50;
int trnSPEED = 40;
int WallHeight = 350;//408 - picks 2 rings;
int PostHeight = 1440;
int InnerLineCorr = 20;

void move(int degrees, int speed)
{
	resetMotorEncoder(LeftMotor);
	resetMotorEncoder(RightMotor);

	while(abs(getMotorEncoder(LeftMotor)) < (degrees) &&
		abs(getMotorEncoder(RightMotor)) < (degrees))
	{
		setMotorSpeed(LeftMotor, speed);
		setMotorSpeed(RightMotor, speed);
	}
	setMotorSpeed(LeftMotor, 0);
	setMotorSpeed(RightMotor, 0);
	sleep(100);
}
//copy
void moveWithCorrection(int degrees, int speed, int correctionInterval) {
	resetMotorEncoder(LeftMotor);
	resetMotorEncoder(RightMotor);
	int originalGyroVal = getGyroDegrees(Gyro);
	int turnSpeed = 40;
	int count = 1;

	while(abs(getMotorEncoder(LeftMotor)) < (degrees) &&
		abs(getMotorEncoder(RightMotor)) < (degrees))
	{
		setMotorSpeed(LeftMotor, speed);
		setMotorSpeed(RightMotor, speed);
		//straight correction
		if(getMotorEncoder(LeftMotor) >= count * correctionInterval ||
			getMotorEncoder(RightMotor) >= count * correctionInterval)
		{
			count++;
			int currentGyroVal = getGyroDegrees(Gyro);
			int straightCorrection = originalGyroVal - currentGyroVal;
			writeDebugStream("Starting Correction. Counter = %d Current Gyro Value = %d\n",count, currentGyroVal);


			while(getGyroDegrees(Gyro) != originalGyroVal) {
				eraseDisplay();
				displayTextLine(1, "Starting Correction.");
				displayTextLine(2, "Counter = %d",count);
				displayTextLine(3, "Gyro Value = %d",currentGyroVal);

				if(currentGyroVal < originalGyroVal) {
					setMotorSpeed(LeftMotor, turnSpeed);
					setMotorSpeed(RightMotor, speed);
				}
				else if(currentGyroVal > originalGyroVal) {
					setMotorSpeed(LeftMotor, speed);
					setMotorSpeed(RightMotor, turnSpeed);
				}
			}
		}
	}
	//normal
	setMotorSpeed(LeftMotor, 0);
	setMotorSpeed(RightMotor, 0);
	sleep(100);
}

void trnLeft(int degrees, int speed)
{
	resetGyro(Gyro);
	int degreeCorrectionL = 1;

	eraseDisplay();

	while(getGyroDegrees(Gyro) <= degrees - degreeCorrectionL)
	{
		setMotorSpeed(LeftMotor, -speed);
		setMotorSpeed(RightMotor, speed);

		displayTextLine(1, "Degrees = %d", degrees);
		displayTextLine(2, "Trn Left = %d", getGyroDegrees(Gyro));
	}
	setMotorSpeed(LeftMotor, 0);
	setMotorSpeed(RightMotor, 0);
	writeDebugStream("Turning Left Value = %d \n", getGyroDegrees(Gyro));

}

void trnRight(int degrees, int speed)
{
	resetGyro(Gyro);
	int degreeCorrectionR = 1;
	eraseDisplay();

	while(getGyroDegrees(Gyro) >= -degrees + degreeCorrectionR)
	{
		setMotorSpeed(LeftMotor, speed);
		setMotorSpeed(RightMotor, -speed);

		displayTextLine(1, "Degrees = %d", degrees);
		displayTextLine(2, "Trn Right = %d", getGyroDegrees(Gyro));
	}
	setMotorSpeed(LeftMotor, 0);
	setMotorSpeed(RightMotor, 0);

	writeDebugStream("Turning Right Value = %d \n", getGyroDegrees(Gyro));
}


void fourBarLift(int degrees, int speed)
{
	resetMotorEncoder(BarLift);

	writeDebugStream("Begin - 4 Bar Lift Height(%d) = %d \n", degrees, getMotorEncoder(BarLift));

	while((degrees > 0 && (getMotorEncoder(BarLift) < degrees)) ||
		(degrees < 0 && (getMotorEncoder(BarLift) > degrees)) ) {
		setMotorSpeed(BarLift, speed);

	}
	setMotorSpeed(BarLift, 0);
	writeDebugStream("End - 4 Bar Lift Height = %d \n", getMotorEncoder(BarLift));
}

void pushMiddleRings(void)
{
	// redefine the speed locally (higher speed)
	int SPEED = 70;

	moveWithCorrection(200, SPEED, 150);
	trnLeft(20,trnSPEED);
	moveWithCorrection(200, SPEED, 150);
	trnRight(18,trnSPEED);

	// Original working version
	//moveWithCorrection(2100, SPEED, 150);
	//moveWithCorrection(2300, -120, 2500);

	// shorten the distance to save 1s
	moveWithCorrection(900, SPEED, 50);
	moveWithCorrection(1000, SPEED + 20, 50)
	moveWithCorrection(2000, -120, 2500);
}


void resolvePeg1Mission(void)
{
	//move to first peg to lift rings
	moveWithCorrection(1300, SPEED, 150);
	trnLeft(85, trnSPEED); //was 86
	fourBarLift(WallHeight + 6, 100);
	moveWithCorrection(480 + InnerLineCorr - 5, SPEED, 500);
	move(35, -20);
	fourBarLift(500, 75);

	// move to first pipe to drop off rings
	moveWithCorrection(220, -SPEED, 150);
	trnRight(175, trnSPEED);   //originally 170
	fourBarLift(675, 75);
	moveWithCorrection(570 - InnerLineCorr, SPEED, 700);//originally 150 correction interval

	//lowering rings onto pipe
	fourBarLift(-300, -50);
	moveWithCorrection(50, -50, 25);
	fourBarLift(-500, -50);
	moveWithCorrection(425, -75, 125);
	fourBarLift(-728, -50);
}

void resolvePeg2Mission_Original(void)
{
	//move to second peg to lift rings
	moveWithCorrection(2420, SPEED, 150);
	trnLeft(86, trnSPEED);
	fourBarLift(WallHeight,100);
	moveWithCorrection(440, SPEED, 500);  //originally 465, too far most of the time
	move(28.8, -20);
	fourBarLift(500, 75);

	// move to second pipe to drop off rings
	moveWithCorrection(200, -SPEED, 150);
	trnRight(175, trnSPEED);
	fourBarLift(615, 75);
	moveWithCorrection(565, SPEED, 150);

	//lowering rings onto pipe
	fourBarLift(-300, -50);
	moveWithCorrection(50, -50, 25);
	fourBarLift(-500, -50);
	moveWithCorrection(375, -SPEED, 125);
	//fourBarLift(-665 + WallHeight, -50); // move to peg3Mission
}

void resolvePeg2Mission(void) {
	//move to second peg to lift rings
	moveWithCorrection(2420, SPEED, 150);
	trnLeft(85, trnSPEED); //was 86
	fourBarLift(WallHeight + 4.5, 100);
	moveWithCorrection(480 + InnerLineCorr - 5, SPEED, 500);
	move(35, -20);
	fourBarLift(500, 75);

	// move to second pipe to drop off rings
	moveWithCorrection(220, -SPEED, 150);
	trnRight(175, trnSPEED);   //originally 180, too much
	fourBarLift(675, 75);
	moveWithCorrection(595 - InnerLineCorr, SPEED, 700);//originally 150 correction interval

	//lowering rings onto pipe
	fourBarLift(-300, -50);
	moveWithCorrection(50, -50, 25);
	fourBarLift(-500, -50);
	moveWithCorrection(425, -75, 125);
	fourBarLift(-728, -50);
}

void resolvePeg3Mission(void)
{
	//move to third peg to lift rings
	fourBarLift(200, 50);
	moveWithCorrection(1130, SPEED, 150);
	trnLeft(85, trnSPEED);
	fourBarLift(-665 - 200+WallHeight, -50);
	//fourBarLift(WallHeight,100);
	moveWithCorrection(470, SPEED, 500);
	move(28.8, -20);
	fourBarLift(500, 75);

	// move to third pipe to drop off rings
	moveWithCorrection(200, -SPEED, 150);
	trnRight(170, trnSPEED);
	fourBarLift(615, 75);
	moveWithCorrection(550, SPEED, 150);

	//lowering rings onto pipe
	fourBarLift(-300, -50);
	moveWithCorrection(50, -50, 25);
	fourBarLift(-500, -50);
	moveWithCorrection(375, -SPEED, 125);

	//fourBarLift(-730, -50);
}


task main()
{
	eraseDisplay();
	//moveWithCorrection(degrees, speed, correction interval);
	//move(degrees, speed);
	//trnLeft(degrees, speed);
	//trnRight(degrees, speed);
	//fourBarLift(degrees, speed);

	// reset motors/sensors
	resetMotorEncoder(BarLift);
	resetGyro(Gyro);
	resetMotorEncoder(LeftMotor);
	resetMotorEncoder(RightMotor);
	clearDebugStream();

	int gyroVal = getGyroDegrees(Gyro);

	// resolve missions
	resolvePeg1Mission();
	sleep(9000);
	resolvePeg2Mission();
	//sleep(6000);
	//trnLeft(85, trnSPEED);
	//resolvePeg3Mission();
	//pushBonusTray();


	gyroVal = getGyroDegrees(Gyro);
	writeDebugStream("Done moving\n");

}
